const thumbnailData = {
    "drop-bar": "thumbnail/Accessories/drop bar/drop-bar-barbell-smartgymequipment-chennai-redhills.webp",
    "landmine": "thumbnail/Accessories/landmine/landmine.webp",
    "slip-squat-adjustable-stand": "thumbnail/Accessories/Slip squat adjustable stand/leg split squat adjustable_result_result.webp",
    "standing-lateral-raise": "thumbnail/Accessories/standing lateral raise/standing lateral raise-plate-loaded-top-smart-gym-equipment.webp",
    "t-bar": "thumbnail/Accessories/t bar/t-bar-top-smart-gym-equipment-chennai-redhills.webp",
    "cable-cross-over": "thumbnail/Multifunctional and functional equipments/Cable cross over/cable-cross-over-machine-smart-gym-equipment.webp",
    "functional-trainer": "thumbnail/Multifunctional and functional equipments/Functional trainer/functional-trainer-with-chest-support-smartgymequipment-chennai-redhills (15).webp",
    "functional-trainer-with-smith": "thumbnail/Multifunctional and functional equipments/functional trainer with smith/functional-trainer-with-smith-machine-smartgymequipment-chennai-redhills (24).webp",
    "5-station-multi-gym": "thumbnail/Multifunctional and functional equipments/multi gym or jungle gym/5 station multi gym/multigym-jungle-gym-smartgymequipment-chennai-redhills.webp",
    "hexagon-type": "thumbnail/Multifunctional and functional equipments/multi gym or jungle gym/Hexagon type/8-station-hexagon-multigym-smartgymequipment-chennai-redhills (1).webp",
    "home-multi-gym\uf028": "thumbnail/Multifunctional and functional equipments/multi gym or jungle gym/Home multi gym\uf028/homegym-smartgymequipment-chennai-redhills (3).webp",
    "it-company-model-1": "thumbnail/Multifunctional and functional equipments/multi gym or jungle gym/IT company model 1/multi-gym-htc-top-smart-gym-equipment-india-tamilnadu-chennai-redhills (4).webp",
    "it-company-model-2": "thumbnail/Multifunctional and functional equipments/multi gym or jungle gym/IT Company model 2/multi gym or jungle gym-top-smart-gym-equipment-india-tamilnadu-chennai-redhills (4).webp",
    "multi-gym-2025": "thumbnail/Multifunctional and functional equipments/multi gym or jungle gym/multi gym 2025/multi-gym-8-station-smartgymequipment-chennai-redhills (2).webp",
    "new-model": "thumbnail/Multifunctional and functional equipments/multi gym or jungle gym/New model/multigym-8-station-jungle-gym-smartgymequipment-chennai-redhills (3).webp",
    "type-(i)": "thumbnail/Multifunctional and functional equipments/multi gym or jungle gym/Type (i)/multi gym or jungle gym-top-smart-gym-equipment-india-tamilnadu-chennai-redhills (1).webp",
    "type-(ii)": "thumbnail/Multifunctional and functional equipments/multi gym or jungle gym/Type (ii)/multigym-jungle-gym-8-station-smartgymequipment-chennai-redhills (7).webp",
    "type-(iii)": "thumbnail/Multifunctional and functional equipments/multi gym or jungle gym/Type (iii)/multigym-8-station-jungle-gym-smartgymequipment-chennai-redhills  (4).webp",
    "type-4-station": "thumbnail/Multifunctional and functional equipments/multi gym or jungle gym/Type 4 station/4-station-multigym-jungle-gym-smartgymequipment-chennai-redhills (2).webp",
    "type-arch": "thumbnail/Multifunctional and functional equipments/multi gym or jungle gym/Type arch/multigym-5-station-smartgymequipment-chennai-redhills (1).webp",
    "type-l": "thumbnail/Multifunctional and functional equipments/multi gym or jungle gym/Type L/multigym-pink-jungle-gym-smartgymequipment-chennai-redhills (3).webp",
    "power-rack-with-smith-machine": "thumbnail/Multifunctional and functional equipments/power rack with smith machine/powerrack-with-smith-machine-smartgymequipment-chennai-redhills (7).webp",
    "smith-machine": "thumbnail/Multifunctional and functional equipments/smith machine/smith-machine-top-smart-gym-equipment-india-tamilnadu-chennai-redhills (11).webp",
    "smith-machine-with-squat-rack": "thumbnail/Multifunctional and functional equipments/smith machine with squat rack/smith machine with squat rack-top-smart-gym-equipment-india-tamilnadu-chennai-redhills (4).webp",
    "triangular-multipurpose-cross-over": "thumbnail/Multifunctional and functional equipments/triangular multipurpose cross over/three-station-triangular-multipurpose-machine-smartgymequipment-chennai-redhills  (4).webp",
    "abdominal-exerciser": "thumbnail/plate loaded equipments/abs exercise machine/abdomen-exerciser-machine-smartgymequipment-chennai-redhills  (5).webp",
    "alternate-seated-biceps-curl": "thumbnail/plate loaded equipments/arms/alternate seated biceps curl/plateloaded-isolateral-prechur-curl-machine-smartgymequipment-chennai-redhills  (18).webp",
    "plate-loaded-tricep-push-down-machine": "thumbnail/plate loaded equipments/arms/Plate loaded tricep push down machine/triceps-pushdown-machine-plateloaded-smartgymequipment-chennai-redhills  (1).webp",
    "prechur-curl": "thumbnail/plate loaded equipments/arms/Prechur curl/prechur-curl-machinetop-smart-gym-equipment-india-chennai-redhills (1).webp",
    "seated-plate-loaded-triceps-extension": "thumbnail/plate loaded equipments/arms/Seated plate loaded triceps extension/plateloaded-seated-triceps-extension-smartgymequipment-chennai-redhills (1).webp",
    "triceps-dips": "thumbnail/plate loaded equipments/arms/triceps dips/plateloaded-seated-triceps-dips-machine-smartgymequipment-chennai-redhills  (5).webp",
    "incline-chest-flies": "thumbnail/plate loaded equipments/Chest/incline chest flies/plate loaded chest flys-top-smart-gym-equipment-india-tamilnadu-chennai-redhills (4).webp",
    "incline-chest-press": "thumbnail/plate loaded equipments/Chest/incline chest press/incline isolateral chest press plate loaded-top-smart-gym-equipment-india-tamilnadu-chennai-redhills (7).webp",
    "isolatral-seated-chest-press": "thumbnail/plate loaded equipments/Chest/isolatral seated chest press/incline isolateral chest press plate loaded-top-smart-gym-equipment-india-tamilnadu-chennai-redhills (11).webp",
    "multi-press": "thumbnail/plate loaded equipments/Chest/multi press/multi chest press machine-top-smart-gym-equipment-india-tamilnadu-chennai-redhills (15).webp",
    "compound-row-machine": "thumbnail/plate loaded equipments/lat/compound row machine/plateloaded-compound-row-machine-smartgymequipment-chennai-redhills  (3).webp",
    "isolatral-row": "thumbnail/plate loaded equipments/lat/isolatral row/plateloaded-rowing-machine-smartgymequipment-chennai-redhills  (15).webp",
    "latpull-down": "thumbnail/plate loaded equipments/lat/latpull down/plateloaded-latpulldown-smartgymequipment-chennai-redhills (6).webp",
    "latpull-down-with-chest-press": "thumbnail/plate loaded equipments/lat/latpull down with chest press/latpulldown-with-chestpress-smartgymequipment-chennai-redhills (3).webp",
    "liner-row-machine": "thumbnail/plate loaded equipments/lat/liner row machine/plateloadede-liner-row-machine-smartgymequipment-chennai-redhills (4).webp",
    "liner-t-bar-row": "thumbnail/plate loaded equipments/lat/liner t-bar row/liner-t-bar-row-machine.webp",
    "low-row": "thumbnail/plate loaded equipments/lat/low row/plateloaded-low-row-machine-smartgymequipment-chennai-redhills (1).webp",
    "plate-loaded-high-pull-down-machine": "thumbnail/plate loaded equipments/lat/Plate loaded high pull down machine/plateloaded-high-pull-down-machine-smartgymequipment-chennai-redhills  (1).webp",
    "reverse-hyper-extension": "thumbnail/plate loaded equipments/lat/reverse hyper extension/reverse-hyper-extension-plateloaded-smartgymequipment-chennai-redhills  (4).webp",
    "reverse-latpull-down-machine": "thumbnail/plate loaded equipments/lat/reverse latpull down machine/plateloaded-reverse-latpull-down-machine-smartgymequipment-chennai-redhills (8).webp",
    "standing-t-bar-row": "thumbnail/plate loaded equipments/lat/standing t bar row/plateloaded-standing-tbar-row-machine-smartgymequipment-chennai-redhills (1).webp",
    "t-bar-row": "thumbnail/plate loaded equipments/lat/t bar row/plateloaded-tbar-row-machine-chest-supported-smartgymequipment-chennai-redhills (12).webp",
    "45-degree-leg-press": "thumbnail/plate loaded equipments/legs/45 degree leg press/legpress-top-smart-gym-equipment-india-tamilnadu-chennai-redhills (17).webp",
    "assisted-glute-ham-raise": "thumbnail/plate loaded equipments/legs/Assisted glute ham raise/assisted glute ham-top-smart-gym-equipment-india-tamilnadu-chennai-redhills.webp",
    "belt-squat": "thumbnail/plate loaded equipments/legs/belt squat/belt squat-machine-top-smart-gym-equipment-india-tamilnadu-chennai-redhills (1).webp",
    "hacksquat": "thumbnail/plate loaded equipments/legs/hacksquat/plate loaded hack squat machine-top-smart-gym-equipment-india-tamilnadu-chennai-redhills (3).webp",
    "leg-curl-and-leg-extension": "thumbnail/plate loaded equipments/legs/leg curl and leg extension/plate loaded leg extension and leg curl machine-top-smart-gym-equipment-india-tamilnadu-chennai-redhills (3).webp",
    "leg-press-leverage-type": "thumbnail/plate loaded equipments/legs/leg press leverage type/legpress-leverage-type-top-smart-gym-equipment-india-tamilnadu-chennai-redhills (3).webp",
    "leg-press-with-hack-squat": "thumbnail/plate loaded equipments/legs/leg press with hack squat/plate loaded leg press with hack squat machine-top-smart-gym-equipment-india-tamilnadu-chennai-redhills (22).webp",
    "pendulum-squat": "thumbnail/plate loaded equipments/legs/pendulum squat/pendulam-squat.webp",
    "power-squat-(or)-v-squat": "thumbnail/plate loaded equipments/legs/power squat (or) v squat/plate loaded power squat or v - squat machine-top-smart-gym-equipment-india-tamilnadu-chennai-redhills (13).webp",
    "seated-calf-raise": "thumbnail/plate loaded equipments/legs/seated calf raise/plate loaded seated calf raise machine-top-smart-gym-equipment-india-tamilnadu-chennai-redhills (8).webp",
    "seated-calf-raise-with-tibia-raise": "thumbnail/plate loaded equipments/legs/Seated calf raise with tibia raise/plateloaded-seated-calf-raise-with-tibia-raise-machine-smartgymequipment (1).webp",
    "swing-squat": "thumbnail/plate loaded equipments/legs/swing squat/plateloaded-swing-squat-machine-smartgymequipment.webp",
    "vertical-leg-press": "thumbnail/plate loaded equipments/legs/vertical leg press/plate loaded vertical legpress machine-top-smart-gym-equipment-india-tamilnadu-chennai-redhills (1).webp",
    "rear-delt-flies-machine": "thumbnail/plate loaded equipments/shoulder/rear delt flies machine/plateloaded-rear-delt-flies-machine-smartgymequipment-chennai-redhills (2).webp",
    "seated-lateral-raise": "thumbnail/plate loaded equipments/shoulder/seated lateral raise/plate loaded lateral raise machine-top-smart-gym-equipment-india-tamilnadu-chennai-redhills (2).webp",
    "seated-shoulder-press-with-lateral-raise-machine": "thumbnail/plate loaded equipments/shoulder/Seated shoulder press with lateral raise machine/shoulder-press-machine-with-lateral-raise-machine-top-smart-gym-equipment-india-chennai-redhills (3).webp",
    "shoulder-press": "thumbnail/plate loaded equipments/shoulder/Shoulder press/plate loaded shoulder press machine-top-smart-gym-equipment-india-tamilnadu-chennai-redhills (36).webp",
    "shrug-machine-with-deadlift": "thumbnail/plate loaded equipments/shoulder/Shrug machine with deadlift/plate loaded shrug machine with deadlift machine-top-smart-gym-equipment-india-tamilnadu-chennai-redhills (12).webp",
    "standing-lateral-raise-machine": "thumbnail/plate loaded equipments/shoulder/Standing lateral raise machine/plate loaded lateral raise machine-top-smart-gym-equipment-india-tamilnadu-chennai-redhills.webp",
    "half-rack": "thumbnail/Racks and rigs/Racks/half rack/half-rack-machine-smartgymequipment-chennai-redhills (1).webp",
    "power-rack": "thumbnail/Racks and rigs/Racks/power rack/power-rack-smartgymequipment-chennai-redhills (19).webp",
    "power-rack-with-smith-machine-racks-and-rigs": "thumbnail/Racks and rigs/Racks/power rack with smith machine/powerrack-with-smith-machine-smartgymequipment-chennai-redhills (7).webp",
    "squat-rack\uf028": "thumbnail/Racks and rigs/Racks/squat rack\uf028/squat-rack-smartgymequipment-chennai-redhills (13).webp",
    "crossfit-cage": "thumbnail/Racks and rigs/Rigs/crossfit cage/crossfit-cage-smartgymequipment-chennai-redhills (18).webp",
    "biceps-prechur-curl": "thumbnail/selectorized equipments/arms/Biceps prechur curl/prechur-curl-machine-smartgymequipment-chennai-redhills  (2).webp",
    "forearm-machine": "thumbnail/selectorized equipments/arms/forearm machine/forearm-machine-new-2026.webp",
    "chest-press": "thumbnail/selectorized equipments/Chest/Chest press/selectorized-seated-chest-press-machine-pinloaded-smartgymequipment-chennai-redhills  (2).webp",
    "multi-press-selectorized-equipments": "thumbnail/selectorized equipments/Chest/Multi press/multi-press-machine-new-2026.webp",
    "peck-fly-with-rear-delt": "thumbnail/selectorized equipments/Chest/peck fly with rear delt/peckfly-with-rear-delt-machine-smartgymequipment-chennai-redhills (7).webp",
    "assisted-chin-ups-and-dips": "thumbnail/selectorized equipments/lat/assisted chin ups and dips/assisted chin ups with dips 2026 new (2).webp",
    "dual-lat-pull-down": "thumbnail/selectorized equipments/lat/dual lat pull down/selectorized-latpulldown-with-dual-pulley-machine-chennai-redhills  (1).webp",
    "latpull-and-row": "thumbnail/selectorized equipments/lat/latpull and row/lat-pull-down-with-rowing -new (4).webp",
    "rowing": "thumbnail/selectorized equipments/lat/rowing/selectorized-pinloaded-rowing-machine-smartgymequipment-chennai-redhills (8).webp",
    "adductor---abductor": "thumbnail/selectorized equipments/legs/Adductor - abductor/selectorized-abductor-and-adductor-machine-smartgymequipment-chennai-redhills (8)_result.webp",
    "leg-curl-and-leg-extension-(-seated---prone-)": "thumbnail/selectorized equipments/legs/leg curl and leg extension ( Seated - prone )/top-seated-prone-legcurl-legextension-machine-smartgymequipment-chennai-redhills  (15).webp",
    "seated-leg-curl-and-leg-extension": "thumbnail/selectorized equipments/legs/seated leg curl and leg extension/selectorized-seated-legcurl-with-legextension-machine-pinloaded-smartgymequipment-chennai-redhills (10).webp",
    "lateral-raise": "thumbnail/selectorized equipments/shoulder/lateral raise/lateral-raise-selecorised-pinloaded-smartgymequipment-chennai-redhills (12).webp",
    "shoulder-press-machine": "thumbnail/selectorized equipments/shoulder/Shoulder press machine/selectorised-multi-press-machine-pinloaded-smartgymequipment-chennai-redhills (9).webp",
    "adjustable-abdomen-bench-2.0": "thumbnail/weight benches and storage/Adjustable abdomen bench 2.0/adjustable abdomen bench v2.0 new 2026 (3).webp",
    "adjustable-abdominal-board": "thumbnail/weight benches and storage/Adjustable abdominal board/adjustable-abdomen-bench-torso-smartgymequipment-chennai-redhills (1).webp",
    "bench-pull": "thumbnail/weight benches and storage/bench pull/bench-pull-machine-smartgymequipment-chennai-redhills.webp",
    "bi---tri-bench": "thumbnail/weight benches and storage/Bi - tri bench/bicep-tricep-bench-smartgymequipment-chennai-redhills (1).webp",
    "completely-adjustable-olympic-fid-bench-press": "thumbnail/weight benches and storage/Completely adjustable olympic fid bench press/complete-adjustable-olympic-fid-bench-press.webp",
    "dumbell-rack-mini": "thumbnail/weight benches and storage/Dumbell rack mini/mini-dumbell-rack.webp",
    "fid-bench": "thumbnail/weight benches and storage/FID bench/flat-incline-decline-bench-smartgymequipment-chennai-redhills (1).webp",
    "flat-bench": "thumbnail/weight benches and storage/flat bench/flat-bench-smartgymequipment-chennai-redhills (3).webp",
    "hyper-extension": "thumbnail/weight benches and storage/hyper extension/hyper-extension-machine-smartgymequipment-chennai-redhills (7).webp",
    "incline-bench": "thumbnail/weight benches and storage/Incline bench/incline-bench-smartgymequipment-chennai-redhills (2).webp",
    "olympic-decline-bench": "thumbnail/weight benches and storage/olympic decline bench/olympic-decline-benchpress-smartgymequipment-chennai-redhills (1).webp",
    "olympic-fid-bench": "thumbnail/weight benches and storage/olympic FID bench/olympic-fid-benchpress-machine-smartgymequipment-chennai-redhills (1).webp",
    "olympic-flat-bench": "thumbnail/weight benches and storage/olympic flat bench/olympic-flat-bench-press-smartgymequipment-chennai-redhills (19).webp",
    "olympic-incline-bench": "thumbnail/weight benches and storage/olympic incline bench/olympic-incline-benchpress-machine-smartgymequipment-chennai-redhills (4).webp",
    "olympic-rod-stand": "thumbnail/weight benches and storage/Olympic rod stand/olympic-barbell-stand-rod-smartgymequipment-chennai-redhills .webp",
    "plate-stand": "thumbnail/weight benches and storage/plate stand/olympic-weight-plate-stand-smartgymequipment-chennai-redhills (1).webp",
    "prechur-curl-manual": "thumbnail/weight benches and storage/prechur curl manual/prechur-curl-bench-machine-smartgymequipment-chennai-redhills (8).webp",
    "seal-row": "thumbnail/weight benches and storage/Seal row/seal-row-bench-machine-smartgymequipment-chennai-redhills (1).webp",
    "sissy-squat": "thumbnail/weight benches and storage/sissy squat/sissy-squat-machine-smartgymequipment-chennai-redhills (3).webp",
    "sitting-standing-twister": "thumbnail/weight benches and storage/sitting standing twister/sitting-standing-twister-smartgymequipment-chennai-redhills (27).webp",
    "sled": "thumbnail/weight benches and storage/sled/sled-smartgymequipment-chennai-redhills (6).webp",
    "three-tier-dumbbell-rack": "thumbnail/weight benches and storage/three tier dumbbell rack/three-tier-dumbell-rackl-smartgymequipment-chennai-redhills (2).webp",
    "total-arm-blaster": "thumbnail/weight benches and storage/Total arm blaster/total-arm-biceps-blaster-smartgymequipment-chennai-redhills.webp",
    "twister": "thumbnail/weight benches and storage/twister/twister-new-2026 (1).webp",
    "two-tier-dumbbell-rack": "thumbnail/weight benches and storage/two tier dumbbell rack/two-tier-dumbell-rack-smartgymequipment-chennai-redhills (2).webp",
    "utility-stool": "thumbnail/weight benches and storage/utility stool/utility-multipurpose-stool-smartgymequipment-chennai-redhills  - copy.webp",
    "vertical-knee-raise": "thumbnail/weight benches and storage/vertical knee raise/vertical-knee-raise-smartgymequipment-chennai-redhills (1).webp",
    "vertical-knee-raise-with-chin-ups": "thumbnail/weight benches and storage/vertical knee raise with chin ups/vertical-knee-raise-with-chin-ups-smartgymequipment-chennai-redhills.webp",
    "weight-lifting-platform": "thumbnail/weight benches and storage/weight lifting platform/weightlifting-platform-smartgymequipment-chennai-redhills (1).webp"
};
