const thumbnailData = {
    "drop-bar": "images/Accessories/drop bar/drop-bar-barbell-smartgymequipment-chennai-redhills.webp",
    "landmine": "images/Accessories/landmine/landmine.webp",
    "split_squat_stand_pin_type": "images/Accessories/Split_squat_stand_pin_type/leg split squat adjustable_result_result.webp",
    "standing-lateral-raise": "thumbnail/Accessories/standing lateral raise/standing lateral raise-plate-loaded-top-smart-gym-equipment.webp",
    "t-bar": "thumbnail/Accessories/t bar/t-bar-top-smart-gym-equipment-chennai-redhills.webp",
    "cable-cross-over": "images/Multifunctional and functional equipments/Cable cross over/20251031_180320.webp",
    "functional-trainer": "images/Multifunctional and functional equipments/Functional trainer/functional-trainer-with-chest-support-smartgymequipment-chennai-redhills (12).webp",
    "functional-trainer-with-smith": "images/Multifunctional and functional equipments/functional trainer with smith/functional-trainer-with-smith-machine-smartgymequipment-chennai-redhills (10).webp",
    "home-multi-gym\uf028": "images/Multifunctional and functional equipments/Multigym or Jungle Gym/Home multi gym\uf028/homegym-smartgymequipment-chennai-redhills (2).webp",
    "multi-gym-2025": "images/Multifunctional and functional equipments/Multigym or Jungle Gym/multi gym 2025/multi-gym-8-station-smartgymequipment-chennai-redhills (2).webp",
    "power-rack-with-smith-machine": "images/Multifunctional and functional equipments/power rack with smith machine/powerrack-with-smith-machine-smartgymequipment-chennai-redhills (10).webp",
    "smith-machine": "images/Multifunctional and functional equipments/smith machine/half-rack-machine-top-smart-gym-equipment-india-tamilnadu-chennai-redhills  (10).webp",
    "smith-machine-with-squat-rack": "thumbnail/Multifunctional and functional equipments/smith machine with squat rack/smith machine with squat rack-top-smart-gym-equipment-india-tamilnadu-chennai-redhills (4).webp",
    "triangular-multipurpose-cross-over": "thumbnail/Multifunctional and functional equipments/triangular multipurpose cross over/three-station-triangular-multipurpose-machine-smartgymequipment-chennai-redhills  (4).webp",
    "abdominal-exerciser": "images/plate loaded equipments/Abs Machines/Abdominal Exerciser/abdomen-exerciser-machine-smartgymequipment-chennai-redhills  (3).webp",
    "low-row": "images/plate loaded equipments/Back Machines/low row/plateloaded-low-row-machine-smartgymequipment-chennai-redhills (1).webp",
    "half-rack": "thumbnail/Racks and rigs/Racks/half rack/half-rack-machine-smartgymequipment-chennai-redhills (1).webp",
    "power-rack": "images/Racks and rigs/Racks/power rack/power-rack-smartgymequipment-chennai-redhills (27).webp",
    "power-rack-with-smith-machine-racks-and-rigs": "thumbnail/Racks and rigs/Racks/power rack with smith machine/powerrack-with-smith-machine-smartgymequipment-chennai-redhills (7).webp",
    "squat-rack\uf028": "thumbnail/Racks and rigs/Racks/squat rack\uf028/squat-rack-smartgymequipment-chennai-redhills (13).webp",
    "crossfit-cage": "thumbnail/Racks and rigs/Rigs/crossfit cage/crossfit-cage-smartgymequipment-chennai-redhills (18).webp",
    "dual-lat-pull-down": "images/selectorized equipments/Back Machines/dual lat pull down/selectorized-latpulldown-with-dual-pulley-machine-chennai-redhills  (6).webp",
    "lateral-raise": "images/selectorized equipments/Shoulder Machines/lateral raise/lateral-raise-selecorised-pinloaded-smartgymequipment-chennai-redhills (12).webp",
    "adjustable-abdomen-bench-2.0": "thumbnail/weight benches and storage/Adjustable abdomen bench 2.0/adjustable abdomen bench v2.0 new 2026 (3).webp",
    "adjustable-abdominal-board": "thumbnail/weight benches and storage/Adjustable abdominal board/adjustable-abdomen-bench-torso-smartgymequipment-chennai-redhills (1).webp",
    "bench-pull": "thumbnail/weight benches and storage/bench pull/bench-pull-machine-smartgymequipment-chennai-redhills.webp",
    "bi---tri-bench": "thumbnail/weight benches and storage/Bi - tri bench/bicep-tricep-bench-smartgymequipment-chennai-redhills (1).webp",
    "completely-adjustable-olympic-fid-bench-press": "thumbnail/weight benches and storage/Completely adjustable olympic fid bench press/complete-adjustable-olympic-fid-bench-press.webp",
    "dumbell-rack-mini": "thumbnail/weight benches and storage/Dumbell rack mini/mini-dumbell-rack.webp",
    "fid-bench": "thumbnail/weight benches and storage/FID bench/flat-incline-decline-bench-smartgymequipment-chennai-redhills (1).webp",
    "flat-bench": "thumbnail/weight benches and storage/flat bench/flat-bench-smartgymequipment-chennai-redhills (3).webp",
    "hyper-extension": "thumbnail/weight benches and storage/hyper extension/hyper-extension-machine-smartgymequipment-chennai-redhills (7).webp",
    "incline-bench": "thumbnail/weight benches and storage/Incline bench/incline-bench-smartgymequipment-chennai-redhills (2).webp",
    "olympic-decline-bench": "thumbnail/weight benches and storage/olympic decline bench/olympic-decline-benchpress-smartgymequipment-chennai-redhills (1).webp",
    "olympic-fid-bench": "thumbnail/weight benches and storage/olympic FID bench/olympic-fid-benchpress-machine-smartgymequipment-chennai-redhills (1).webp",
    "olympic-flat-bench": "thumbnail/weight benches and storage/olympic flat bench/olympic-flat-bench-press-smartgymequipment-chennai-redhills (19).webp",
    "olympic-incline-bench": "thumbnail/weight benches and storage/olympic incline bench/olympic-incline-benchpress-machine-smartgymequipment-chennai-redhills (4).webp",
    "olympic-rod-stand": "thumbnail/weight benches and storage/Olympic rod stand/olympic-barbell-stand-rod-smartgymequipment-chennai-redhills .webp",
    "plate-stand": "thumbnail/weight benches and storage/plate stand/olympic-weight-plate-stand-smartgymequipment-chennai-redhills (1).webp",
    "prechur-curl-manual": "thumbnail/weight benches and storage/prechur curl manual/prechur-curl-bench-machine-smartgymequipment-chennai-redhills (8).webp",
    "seal-row": "thumbnail/weight benches and storage/Seal row/seal-row-bench-machine-smartgymequipment-chennai-redhills (1).webp",
    "sissy-squat": "thumbnail/weight benches and storage/sissy squat/sissy-squat-machine-smartgymequipment-chennai-redhills (3).webp",
    "sitting-standing-twister": "thumbnail/weight benches and storage/sitting standing twister/sitting-standing-twister-smartgymequipment-chennai-redhills (27).webp",
    "sled": "thumbnail/weight benches and storage/sled/sled-smartgymequipment-chennai-redhills (6).webp",
    "three-tier-dumbbell-rack": "thumbnail/weight benches and storage/three tier dumbbell rack/three-tier-dumbell-rackl-smartgymequipment-chennai-redhills (2).webp",
    "total-arm-blaster": "images/weight benches and storage/Total arm blaster/total-arm-biceps-blaster-smartgymequipment-chennai-redhills.webp",
    "twister": "thumbnail/weight benches and storage/twister/twister-new-2026 (1).webp",
    "two-tier-dumbbell-rack": "thumbnail/weight benches and storage/two tier dumbbell rack/two-tier-dumbell-rack-smartgymequipment-chennai-redhills (2).webp",
    "utility-stool": "thumbnail/weight benches and storage/utility stool/utility-multipurpose-stool-smartgymequipment-chennai-redhills  - copy.webp",
    "vertical-knee-raise": "thumbnail/weight benches and storage/vertical knee raise/vertical-knee-raise-smartgymequipment-chennai-redhills (1).webp",
    "vertical-knee-raise-with-chin-ups": "thumbnail/weight benches and storage/vertical knee raise with chin ups/vertical-knee-raise-with-chin-ups-smartgymequipment-chennai-redhills.webp",
    "weight-lifting-platform": "thumbnail/weight benches and storage/weight lifting platform/weightlifting-platform-smartgymequipment-chennai-redhills (1).webp",
    "category:Accessories": "images/Accessories/Split_squat_stand_pin_type/leg split squat adjustable_result_result.webp",
    "category:plate loaded equipments": "images/plate loaded equipments/Back Machines/low row/plateloaded-low-row-machine-smartgymequipment-chennai-redhills (1).webp",
    "category:selectorized equipments": "images/selectorized equipments/Shoulder Machines/lateral raise/lateral-raise-selecorised-pinloaded-smartgymequipment-chennai-redhills (12).webp",
    "category:Racks and rigs": "images/Racks and rigs/Racks/power rack/power-rack-smartgymequipment-chennai-redhills (27).webp",
    "category:weight benches and storage": "images/weight benches and storage/Total arm blaster/total-arm-biceps-blaster-smartgymequipment-chennai-redhills.webp",
    "category:Multifunctional and functional equipments": "images/Multifunctional and functional equipments/functional trainer with smith/functional-trainer-with-smith-machine-smartgymequipment-chennai-redhills (19).webp",
    "subcategory:lat": "images/selectorized equipments/Back Machines/dual lat pull down/selectorized-latpulldown-with-dual-pulley-machine-chennai-redhills  (6).webp",
    "subcategory:Racks": "images/Racks and rigs/Racks/power rack/power-rack-smartgymequipment-chennai-redhills (27).webp",
    "subcategory:Total arm blaster": "images/weight benches and storage/Total arm blaster/total-arm-biceps-blaster-smartgymequipment-chennai-redhills.webp",
    "subcategory:Cable cross over": "images/Multifunctional and functional equipments/Cable cross over/20251031_180320.webp",
    "subcategory:Split_squat_stand_pin_type": "images/Accessories/Split_squat_stand_pin_type/leg split squat adjustable_result_result.webp",
    "subcategory:Functional trainer": "images/Multifunctional and functional equipments/Functional trainer/functional-trainer-with-chest-support-smartgymequipment-chennai-redhills (9).webp",
    "subcategory:power rack with smith machine": "images/Multifunctional and functional equipments/power rack with smith machine/powerrack-with-smith-machine-smartgymequipment-chennai-redhills (2).webp",
    "subcategory:smith machine": "images/Multifunctional and functional equipments/smith machine/half-rack-machine-top-smart-gym-equipment-india-tamilnadu-chennai-redhills  (4).webp",
    "subcategory:functional trainer with smith": "images/Multifunctional and functional equipments/functional trainer with smith/functional-trainer-with-smith-machine-smartgymequipment-chennai-redhills (10).webp"
};
